### ISSUE TITLE
The ssh private key format is inconsistent with the PUTTYGEN client

### ISSUE THREAD

**Issue by Varorbc** [darinkes/SshNet.Keygen#11]
The ssh private key format is inconsistent with the PUTTYGEN client

**Comment by darinkes** [comment]
Your code? You sure you used ToPuttyFormat()?

**Comment by darinkes** [comment]
> I was in a bit of a hurry, I'm really sorry, I saw your work, tomorrow I will use your branch to test, again thanks, I'm going to close the issue.

Would be awesome if you could test the branch. Quite some rework for the PuTTY-Area. :+1:
