### ISSUE TITLE
move sshnet.puttyfile to sshnet.keygen

### ISSUE THREAD

**Issue by Varorbc** [darinkes/SshNet.Keygen#13]
I also used puttyfile, but there were only two files in the project, and I found the same dependencies as the current project, Is it possible to incorporate them, even Agent, as an extension of SSH. NET.

**Comment by darinkes** [comment]
Possible sure, wanted no. Smaller and cleaner codebase for each extension. And not everybody needs all the features.

Whats the issue with using multiple nugets you need for your project?

**Comment by darinkes** [comment]
Package install is so easy, I can't see any struggle.
Your definition of "everything" is different to other people definition. Bloated libs are the worst IMHO, size and complexity.

I'm quite good with git and I'm not doing this for stars.
