### ISSUE TITLE
RSA Key Encryption

### ISSUE THREAD

**Issue by mPisano** [darinkes/SshNet.Keygen#2]
Great Project! Any non synced updates to this?

I rolled some of your changes in to the current SSH.NET, but  
the case:(s) for Key names are off  (ie "Renci.SshNet.Security.RsaKey" vs  "ssh-rsa")

Also Looking for RSA Key encryption?
 
Regards,
Mike

**Comment by darinkes** [comment]
> Great Project! Any non synced updates to this?

Haven't looked at it for a while now tbh. Its quite challenging and time consuming to get changes/features upstream.

> I rolled some of your changes in to the current SSH.NET, but the case:(s) for Key names are off (ie "Renci.SshNet.Security.RsaKey" vs "ssh-rsa")

Sounds like you missed the ToString() override: https://github.com/darinkes/SSH.NET-1/blob/agent_auth/src/Renci.SshNet/Security/Cryptography/RsaKey.cs#L16

> Also Looking for RSA Key encryption?

What do you mean by that? You can already encrypt RSA-Keys.
https://github.com/darinkes/SshNet.Keygen#generate-an-password-protected-rsa-2048-key-in-file-show-the-public-key-and-connect-with-the-private-key

**Comment by darinkes** [comment]
Updated the project to use the official current SSH.NET Release 2023.

**Comment by mPisano** [comment]
Sorry I never followed up and thanks! My SSL project got delayed with other pressing stuff.
Will be rolling these changes into my project and see how it builds. Thanks again!

**Comment by mPisano** [comment]
Looks like I sill have to stick with the older code for now because I still require Framework 4.0... at least there is an upgrade path

**Comment by mPisano** [comment]
I think part of my issue your SSH.NET-1 develop branch seems to be missing all the March 14 commit.

https://github.com/darinkes/SSH.NET-1/tree/f7fad2682e827d585a9c17d7011e6cf22130578e

This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
Add IPrivateKeyFile
So Extension can add own PrivateKeyFiles, e.g. PuttyKeyFile.
@[darinkes](https://github.com/darinkes/SSH.NET-1/commits?author=darinkes)
darinkes committed on Mar 14, 2021 
1 parent [3e5dbc3](https://github.com/darinkes/SSH.NET-1/commit/3e5dbc39e5e2d7ad08e004a00454aa7adc41f1b2)
commit ce48377

It's building now that I pulled SSH.NET-1 from the Keygen.
HTH,
Mike

**Comment by darinkes** [comment]
> Looks like I sill have to stick with the older code for now because I still require Framework 4.0... at least there is an upgrade path

SSH.NET (and microsoft) dropped Support for .NET 4.0. I guess you are on your own then, sorry.

**Comment by mPisano** [comment]
I know, unfortunately I have a few older servers. Luckily they will be upgraded "soon" and I have your older version working now that I found your SSH version with IPrivateKeyFile. 

One of my initial, probably misleading questions was about RSA encryption. It was more about the Format of the keyfile format (ie BEGIN RSA PRIVATE KEY vs PUTTY or SSH) as I read more and more about encryption algorithms and PEM and PKCS versions I really appreciate the work you have done!
  
Given the fact that I'm using older versions (for now) , I have a service provider who wants me to switch from FTP to sFTP and I need to give them a keyfile for when I connect to them. What should I use for "Decent" security (ie not financial or HIPPA)?  Assume OpenSSH format and  possibly RSA-2048  or  ECDSA-256...? or Do I really need to ask them what encryption they support and find a common one... Like VPN tunnels would with the IKE and IPsec SA's...
Appreciate the guidance, Mike

**Comment by darinkes** [comment]
Depends, the ssh daemon can be limited to what kind of auth-keys it accepts.
I usually go with ED25519-keys since they are smaller, but not all ssh-services accept them.

Also ECDSA is suprisingly still not accepted by everyone. RSA (minimum 2048 bits) should be a safe bet.
But RSA, ED25519 and ECDSA should be fine from security perspective.

Export-Format is just putty not the standard. PEM should be the safe path here.
