### ISSUE TITLE
Generate Password-protected file generates normal key

### ISSUE THREAD

**Issue by JoelHer** [darinkes/SshNet.Keygen#6]
When generating a key pair with the following code:
```
var keyInfo = new SshKeyGenerateInfo
{
    KeyFormat = SshKeyFormat.PuTTY,
    Encryption = new SshKeyEncryptionAes256("12345")
};
var key = SshKey.Generate("test.ppk", FileMode.Create, keyInfo);

var publicKey = key.ToPublic();
var fingerprint = key.Fingerprint();
var putty = key.ToPuttyFormat();

Console.WriteLine(putty);
```
The output of the putty key file says there is no encryption on the file, and I can even use no passphrase to connect to the server.
```
PuTTY-User-Key-File-2: ssh-rsa
Encryption: none
Comment: username@devicename
Public-Lines: 6
AAAAB3NzaC1yc2EAAAADAQABAAABAQCqndBjN3SLXONx/R4LzwTRTZPqJUghtq1L
YJLPZgUqftQQ8L18c//I8EwOoVF04Qc4zSBuOhwojPA0GOrrBzyEtqKkTxRJlAOu
2Kz5dAvEhDgCH3eN4J8RoGypCaB1gTz5jW+oLvGU0fcwhJc8ocP8KrT80J1rhKGD
La36gn3QYnf3OEzXVWaT3phuPM0cv3/JZUOiFkMpfobcJw/uOqevqgbnwO7Ni5+Z
uNMi9MbDJX+zWB920jN3lscX02yP9ETW8/mjPLRMO1N28LPkp5IVjkr3PctmtND/
wWIAq3XzfWcMsxkdem9SIFdDumWO8+FNY+EqmtnnlBLaW7TvT621
Private-Lines: 14
AAABAFy7UZvbdDiaz/QQgtggOJoZ9B77DG1mgGHLp3+aD4y9Sj262wJdedSY5n29
KCzCcc5pjwraApv3nkZylJwRXs8zBMsRQBGNpULO+ZTLgenZgyeEOtKeF1bZPrXR
SakUCTQJr3pVqXAdfqCcMCcANSlFfQE70ZOyjqZhmYHiksdDGoBdDcAEr9hK06QW
QsgCLXdcqOj/CYH+3bP2rRGhdOBQ4/7cE4cRyloK6vQPrklsI59BKFQZ+eBD7t1/
/Re+xoOg4QAECkMNAkE7BfzAg3yRPyHcM9oQnmxs6jWidbuUtSymxiZTsA8UmG9V
mF1GBiSx1gXyt/pY1yraF+7eBzEAAACBAM0oPMrnR0C1vlqbkzFpYyeZJZKjRy2d
p3elclRD7gRBO11cQeFbTOSxEwdzYtXgqaREpdxddNd0AqSrisShJbjJge1BplSm
HXNXUPhF3oP+ixFQAQR+aOnsMPEpZfv8FfT+/aO3+fg1ldKOqoMkTYzVNymUbTdA
yUZaRWnOFOnLAAAAgQDU5jbFQfDEwBCwejEMNB2bIZnQZ6cipdqvD3ZfGEVKKAtz
eM9FTz/XUBoo84o4OqLcTJiByghdzxnKKBofjgN8Bc2MY577S+k6jF442QK4usi5
s+uF674sCP1gWZwKd6jezAyLaNLIN9jNaUScOO1tfUNhM2UpliQqRzb1toDWfwAA
AIAIDvVgw9pIpCPcBUmWU1hVwr83jZZqazuk5XMLBxrtKVU9cYosF3kp5sb5C5WH
knw91x08H6eT7zlCNMgBMwq197fG62F4TjZRy2hVcR/+PSqFTdVSwUYi4J5+QI7I
qYDzLEl5tMangrd4DCo4lSuBO1o+RcXtRESkuakER3JfaAECAwQFBgcICQoLDA0O
Private-MAC: 679b164a38d55c8f8b0f89b2e7d1213449bb47cb
```

**Comment by darinkes** [comment]
The encryption gets applied to the generated "test.ppk"-File.

The ToPuttyFormat() and ToOpenSshFormat() are a extension to the SSH.NET PrivateKey-Class and cannot respect the informations from SshKeyGenerateInfo.

**Comment by darinkes** [comment]
Maybe the changes in https://github.com/darinkes/SshNet.Keygen/pull/7 makes it behave more like you expected it?

**Comment by JoelHer** [comment]
Sorry, yes I was confused with generated and parsed keys, but thank you for the clarification.

**Comment by darinkes** [comment]
> Sorry, yes I was confused with generated and parsed keys, but thank you for the clarification.

Do you think the change https://github.com/darinkes/SshNet.Keygen/pull/7  would improve the UX of the API?

Kinda tough to decide what user expects from crypto :)

**Comment by JoelHer** [comment]
> Do you think the change https://github.com/darinkes/SshNet.Keygen/pull/7 would improve the UX of the API?

Yes, I think it's better like that

By the way, thank you for making this library. It's the only library that I could use to generate keys, and there is no other library that does it so simple. Thanks :D

**Comment by darinkes** [comment]
Very kind of you 👍
Feedback and PRs are always welcome.

Cool, thanks for the input. I will merge this improvement ASAP. I hopy there will be an official release soon.
